import {
  Github,
  Slack,
  Database,
  MessageSquare,
  Server,
  CheckCircle,
  User,
  Calendar,
  Mail,
  Building,
  Users,
  FileText,
  BarChart3,
  Zap,
  Globe,
} from "lucide-react";
import React from "react";

export interface MCP {
  id: string;
  name: string;
  version: string;
  visibility: "public" | "private";
  description: string;
  icon: React.ElementType;
  category: string;
  author: string;
  downloads: string;
  lastUpdated: string;
  capabilities: string[];
  mentions: string[];
  documentation: string;
  status: "active" | "beta" | "deprecated";
}

export const availableMCPs: MCP[] = [
  {
    id: "deepwiki",
    name: "DeepWiki MCP",
    version: "v1.0.0",
    visibility: "public",
    description: "Fetch and crawl documentation from deepwiki.com",
    icon: Globe,
    category: "Documentation",
    author: "regenrek",
    downloads: "890",
    lastUpdated: "2024-01-20",
    capabilities: [
      "deepwiki_fetch",
      "crawl_pages",
      "convert_markdown",
      "search_documentation",
    ],
    mentions: [
      "@deepwiki_mcp_fetch",
      "@deepwiki_mcp_crawl_pages",
      "@deepwiki_mcp_convert_markdown",
      "@deepwiki_mcp_search_documentation",
    ],
    documentation: "https://github.com/regenrek/deepwiki-mcp",
    status: "active",
  },
  {
    id: "github",
    name: "GitHub MCP",
    version: "v2.1.4",
    visibility: "public",
    description: "Git repository management and issue tracking",
    icon: Github,
    category: "Developer Tools",
    author: "GitHub Inc.",
    downloads: "125.4K",
    lastUpdated: "2024-01-18",
    capabilities: [
      "read_repos",
      "create_issues",
      "manage_prs",
      "webhook_handling",
    ],
    mentions: [
      "@github_mcp_read_repos",
      "@github_mcp_create_issues",
      "@github_mcp_manage_prs",
      "@github_mcp_webhook_handling",
    ],
    documentation: "https://docs.github.com/mcp",
    status: "active",
  },
  {
    id: "slack",
    name: "Slack MCP",
    version: "v1.8.2",
    visibility: "public",
    description: "Team communication and channel management",
    icon: Slack,
    category: "Communication",
    author: "Slack Technologies",
    downloads: "98.7K",
    lastUpdated: "2024-01-16",
    capabilities: [
      "send_messages",
      "create_channels",
      "manage_users",
      "file_sharing",
    ],
    mentions: [
      "@slack_mcp_send_messages",
      "@slack_mcp_create_channels",
      "@slack_mcp_manage_users",
      "@slack_mcp_file_sharing",
    ],
    documentation: "https://api.slack.com/mcp",
    status: "active",
  },
  {
    id: "datadog",
    name: "Datadog MCP",
    version: "v3.2.1",
    visibility: "public",
    description: "Application performance monitoring and logging",
    icon: Database,
    category: "Monitoring",
    author: "Datadog Inc.",
    downloads: "67.2K",
    lastUpdated: "2024-01-15",
    capabilities: [
      "query_metrics",
      "create_dashboards",
      "set_alerts",
      "log_analysis",
    ],
    mentions: [
      "@datadog_mcp_query_metrics",
      "@datadog_mcp_create_dashboards",
      "@datadog_mcp_set_alerts",
      "@datadog_mcp_log_analysis",
    ],
    documentation: "https://docs.datadoghq.com/mcp",
    status: "active",
  },
  {
    id: "pagerduty",
    name: "PagerDuty MCP",
    version: "v2.4.3",
    visibility: "public",
    description: "Incident management and alerting",
    icon: Server,
    category: "DevOps",
    author: "PagerDuty Inc.",
    downloads: "45.8K",
    lastUpdated: "2024-01-12",
    capabilities: [
      "create_incidents",
      "manage_schedules",
      "escalation_policies",
      "service_management",
    ],
    mentions: [
      "@pagerduty_mcp_create_incidents",
      "@pagerduty_mcp_manage_schedules",
      "@pagerduty_mcp_escalation_policies",
      "@pagerduty_mcp_service_management",
    ],
    documentation: "https://developer.pagerduty.com/mcp",
    status: "active",
  },
  {
    id: "jira",
    name: "Jira MCP",
    version: "v1.9.8",
    visibility: "public",
    description: "Project management and issue tracking",
    icon: CheckCircle,
    category: "Project Management",
    author: "Atlassian",
    downloads: "134.1K",
    lastUpdated: "2024-01-19",
    capabilities: [
      "create_tickets",
      "manage_sprints",
      "project_tracking",
      "workflow_automation",
    ],
    mentions: [
      "@jira_mcp_create_tickets",
      "@jira_mcp_manage_sprints",
      "@jira_mcp_project_tracking",
      "@jira_mcp_workflow_automation",
    ],
    documentation: "https://developer.atlassian.com/mcp",
    status: "active",
  },
  {
    id: "aws",
    name: "AWS MCP",
    version: "v4.1.2",
    visibility: "public",
    description: "Amazon Web Services integration",
    icon: Database,
    category: "Cloud",
    author: "Amazon Web Services",
    downloads: "201.5K",
    lastUpdated: "2024-01-17",
    capabilities: [
      "ec2_management",
      "s3_operations",
      "lambda_functions",
      "cloudwatch_metrics",
    ],
    mentions: [
      "@aws_mcp_ec2_management",
      "@aws_mcp_s3_operations",
      "@aws_mcp_lambda_functions",
      "@aws_mcp_cloudwatch_metrics",
    ],
    documentation: "https://docs.aws.amazon.com/mcp",
    status: "active",
  },
  {
    id: "notion",
    name: "Notion MCP",
    version: "v1.3.5",
    visibility: "public",
    description: "Knowledge management and documentation",
    icon: MessageSquare,
    category: "Productivity",
    author: "Notion Labs",
    downloads: "76.3K",
    lastUpdated: "2024-01-14",
    capabilities: [
      "create_pages",
      "manage_databases",
      "content_search",
      "team_collaboration",
    ],
    mentions: [
      "@notion_mcp_create_pages",
      "@notion_mcp_manage_databases",
      "@notion_mcp_content_search",
      "@notion_mcp_team_collaboration",
    ],
    documentation: "https://developers.notion.com/mcp",
    status: "active",
  },
  {
    id: "temporal",
    name: "Temporal MCP",
    version: "v2.0.9",
    visibility: "private",
    description: "Workflow orchestration and durable execution",
    icon: Server,
    category: "Orchestration",
    author: "Temporal Technologies",
    downloads: "1.2K",
    lastUpdated: "2024-01-08",
    capabilities: [
      "start_workflows",
      "query_workflows",
      "manage_schedules",
      "handle_signals",
    ],
    mentions: [
      "@temporal_mcp_start_workflows",
      "@temporal_mcp_query_workflows",
      "@temporal_mcp_manage_schedules",
      "@temporal_mcp_handle_signals",
    ],
    documentation: "https://temporal.io/docs/mcp",
    status: "active",
  },
  {
    id: "salesforce",
    name: "Salesforce MCP",
    version: "v1.5.7",
    visibility: "private",
    description: "CRM integration and customer data management",
    icon: Building,
    category: "CRM",
    author: "Internal Team",
    downloads: "892",
    lastUpdated: "2024-01-14",
    capabilities: [
      "query_records",
      "create_cases",
      "update_contacts",
      "manage_leads",
    ],
    mentions: [
      "@salesforce_mcp_query_records",
      "@salesforce_mcp_create_cases",
      "@salesforce_mcp_update_contacts",
      "@salesforce_mcp_manage_leads",
    ],
    documentation: "/docs/internal/salesforce-mcp",
    status: "active",
  },
  {
    id: "intercom",
    name: "Intercom MCP",
    version: "v2.2.1",
    visibility: "public",
    description: "Customer support and messaging",
    icon: MessageSquare,
    category: "Support",
    author: "Intercom Inc.",
    downloads: "24.3K",
    lastUpdated: "2024-01-16",
    capabilities: [
      "send_messages",
      "create_tickets",
      "manage_conversations",
      "track_users",
    ],
    mentions: [
      "@intercom_mcp_send_messages",
      "@intercom_mcp_create_tickets",
      "@intercom_mcp_manage_conversations",
      "@intercom_mcp_track_users",
    ],
    documentation: "https://developers.intercom.com/mcp",
    status: "active",
  },
  {
    id: "kubernetes",
    name: "Kubernetes MCP",
    version: "v1.9.4",
    visibility: "private",
    description: "Container orchestration and cluster management",
    icon: Server,
    category: "Infrastructure",
    author: "DevOps Team",
    downloads: "756",
    lastUpdated: "2024-01-11",
    capabilities: [
      "deploy_apps",
      "manage_pods",
      "scale_resources",
      "monitor_cluster",
    ],
    mentions: [
      "@kubernetes_mcp_deploy_apps",
      "@kubernetes_mcp_manage_pods",
      "@kubernetes_mcp_scale_resources",
      "@kubernetes_mcp_monitor_cluster",
    ],
    documentation: "/docs/internal/kubernetes-mcp",
    status: "active",
  },
  {
    id: "prometheus",
    name: "Prometheus MCP",
    version: "v2.7.0",
    visibility: "public",
    description: "Metrics collection and alerting",
    icon: CheckCircle,
    category: "Monitoring",
    author: "Prometheus Community",
    downloads: "41.8K",
    lastUpdated: "2024-01-13",
    capabilities: [
      "query_metrics",
      "create_alerts",
      "manage_targets",
      "export_data",
    ],
    mentions: [
      "@prometheus_mcp_query_metrics",
      "@prometheus_mcp_create_alerts",
      "@prometheus_mcp_manage_targets",
      "@prometheus_mcp_export_data",
    ],
    documentation: "https://prometheus.io/docs/mcp",
    status: "active",
  },
  {
    id: "custom-auth",
    name: "Custom Auth MCP",
    version: "v0.3.2",
    visibility: "private",
    description: "Internal authentication and user management",
    icon: User,
    category: "Security",
    author: "Security Team",
    downloads: "342",
    lastUpdated: "2024-01-09",
    capabilities: [
      "validate_tokens",
      "manage_sessions",
      "audit_access",
      "enforce_policies",
    ],
    mentions: [
      "@custom_auth_validate_tokens",
      "@custom_auth_manage_sessions",
      "@custom_auth_audit_access",
      "@custom_auth_enforce_policies",
    ],
    documentation: "/docs/internal/auth-mcp",
    status: "beta",
  },
  {
    id: "company-database",
    name: "Company Database MCP",
    version: "v1.2.8",
    visibility: "private",
    description: "Internal company data queries and operations",
    icon: Database,
    category: "Internal",
    author: "Data Team",
    downloads: "567",
    lastUpdated: "2024-01-17",
    capabilities: [
      "query_employees",
      "fetch_projects",
      "generate_reports",
      "sync_data",
    ],
    mentions: [
      "@company_db_query_employees",
      "@company_db_fetch_projects",
      "@company_db_generate_reports",
      "@company_db_sync_data",
    ],
    documentation: "/docs/internal/company-db-mcp",
    status: "active",
  },
  // New MCPs for different solution areas
  {
    id: "calendly",
    name: "Calendly MCP",
    version: "v1.4.2",
    visibility: "public",
    description: "Meeting scheduling and calendar management",
    icon: Calendar,
    category: "Scheduling",
    author: "Calendly Inc.",
    downloads: "32.1K",
    lastUpdated: "2024-01-15",
    capabilities: [
      "schedule_meeting",
      "manage_availability",
      "send_invites",
      "track_rsvps",
    ],
    mentions: [
      "@calendly_mcp_schedule_meeting",
      "@calendly_mcp_manage_availability",
      "@calendly_mcp_send_invites",
      "@calendly_mcp_track_rsvps",
    ],
    documentation: "https://developer.calendly.com/mcp",
    status: "active",
  },
  {
    id: "mailchimp",
    name: "Mailchimp MCP",
    version: "v2.1.3",
    visibility: "public",
    description: "Email marketing and campaign management",
    icon: Mail,
    category: "Marketing",
    author: "Mailchimp Inc.",
    downloads: "28.7K",
    lastUpdated: "2024-01-14",
    capabilities: [
      "get_campaign_reports",
      "create_campaigns",
      "manage_subscribers",
      "track_engagement",
    ],
    mentions: [
      "@mailchimp_mcp_get_campaign_reports",
      "@mailchimp_mcp_create_campaigns",
      "@mailchimp_mcp_manage_subscribers",
      "@mailchimp_mcp_track_engagement",
    ],
    documentation: "https://developer.mailchimp.com/mcp",
    status: "active",
  },
  {
    id: "hubspot",
    name: "HubSpot MCP",
    version: "v2.0.8",
    visibility: "public",
    description: "Marketing, sales, and CRM platform",
    icon: Building,
    category: "CRM",
    author: "HubSpot Inc.",
    downloads: "45.2K",
    lastUpdated: "2024-01-16",
    capabilities: [
      "get_contact",
      "create_workflow",
      "manage_deals",
      "track_analytics",
    ],
    mentions: [
      "@hubspot_mcp_get_contact",
      "@hubspot_mcp_create_workflow",
      "@hubspot_mcp_manage_deals",
      "@hubspot_mcp_track_analytics",
    ],
    documentation: "https://developers.hubspot.com/mcp",
    status: "active",
  },
  {
    id: "bamboohr",
    name: "BambooHR MCP",
    version: "v1.7.1",
    visibility: "private",
    description: "HR management and employee data",
    icon: Users,
    category: "HR",
    author: "BambooHR Inc.",
    downloads: "1.8K",
    lastUpdated: "2024-01-12",
    capabilities: [
      "get_applications",
      "manage_employees",
      "track_time_off",
      "generate_reports",
    ],
    mentions: [
      "@bamboohr_mcp_get_applications",
      "@bamboohr_mcp_manage_employees",
      "@bamboohr_mcp_track_time_off",
      "@bamboohr_mcp_generate_reports",
    ],
    documentation: "https://www.bamboohr.com/api/mcp",
    status: "active",
  },
  {
    id: "greenhouse",
    name: "Greenhouse MCP",
    version: "v1.5.4",
    visibility: "public",
    description: "Applicant tracking and recruitment",
    icon: FileText,
    category: "HR",
    author: "Greenhouse Software",
    downloads: "3.2K",
    lastUpdated: "2024-01-13",
    capabilities: [
      "get_candidates",
      "manage_jobs",
      "track_applications",
      "schedule_interviews",
    ],
    mentions: [
      "@greenhouse_mcp_get_candidates",
      "@greenhouse_mcp_manage_jobs",
      "@greenhouse_mcp_track_applications",
      "@greenhouse_mcp_schedule_interviews",
    ],
    documentation: "https://developers.greenhouse.io/mcp",
    status: "active",
  },
  {
    id: "google-analytics",
    name: "Google Analytics MCP",
    version: "v2.3.1",
    visibility: "public",
    description: "Web analytics and performance tracking",
    icon: BarChart3,
    category: "Analytics",
    author: "Google",
    downloads: "89.4K",
    lastUpdated: "2024-01-17",
    capabilities: [
      "get_metrics",
      "track_events",
      "analyze_traffic",
      "generate_reports",
    ],
    mentions: [
      "@google_analytics_mcp_get_metrics",
      "@google_analytics_mcp_track_events",
      "@google_analytics_mcp_analyze_traffic",
      "@google_analytics_mcp_generate_reports",
    ],
    documentation: "https://developers.google.com/analytics/mcp",
    status: "active",
  },
  {
    id: "openai",
    name: "OpenAI MCP",
    version: "v1.8.5",
    visibility: "public",
    description: "AI model integration and content generation",
    icon: Zap,
    category: "AI",
    author: "OpenAI",
    downloads: "156.7K",
    lastUpdated: "2024-01-18",
    capabilities: [
      "generate_content",
      "analyze_text",
      "create_embeddings",
      "moderate_content",
    ],
    mentions: [
      "@openai_mcp_generate_content",
      "@openai_mcp_analyze_text",
      "@openai_mcp_create_embeddings",
      "@openai_mcp_moderate_content",
    ],
    documentation: "https://platform.openai.com/docs/mcp",
    status: "active",
  },
  {
    id: "pipedrive",
    name: "Pipedrive MCP",
    version: "v1.6.2",
    visibility: "public",
    description: "Sales pipeline and deal management",
    icon: Building,
    category: "CRM",
    author: "Pipedrive Inc.",
    downloads: "12.3K",
    lastUpdated: "2024-01-15",
    capabilities: [
      "manage_deals",
      "track_activities",
      "update_pipeline",
      "generate_reports",
    ],
    mentions: [
      "@pipedrive_mcp_manage_deals",
      "@pipedrive_mcp_track_activities",
      "@pipedrive_mcp_update_pipeline",
      "@pipedrive_mcp_generate_reports",
    ],
    documentation: "https://developers.pipedrive.com/mcp",
    status: "active",
  },
  {
    id: "zendesk",
    name: "Zendesk MCP",
    version: "v2.0.3",
    visibility: "public",
    description: "Customer service and support ticketing",
    icon: MessageSquare,
    category: "Support",
    author: "Zendesk Inc.",
    downloads: "18.9K",
    lastUpdated: "2024-01-14",
    capabilities: [
      "create_tickets",
      "manage_conversations",
      "track_satisfaction",
      "generate_reports",
    ],
    mentions: [
      "@zendesk_mcp_create_tickets",
      "@zendesk_mcp_manage_conversations",
      "@zendesk_mcp_track_satisfaction",
      "@zendesk_mcp_generate_reports",
    ],
    documentation: "https://developer.zendesk.com/mcp",
    status: "active",
  },
  {
    id: "instagram",
    name: "Instagram MCP",
    version: "v1.2.0",
    visibility: "public",
    description: "Instagram campaign management and analytics",
    icon: MessageSquare,
    category: "Social Media",
    author: "Meta Platforms",
    downloads: "34.6K",
    lastUpdated: "2024-01-16",
    capabilities: [
      "get_campaigns",
      "analyze_performance",
      "create_content",
      "track_engagement",
    ],
    mentions: [
      "@instagram_mcp_get_campaigns",
      "@instagram_mcp_analyze_performance",
      "@instagram_mcp_create_content",
      "@instagram_mcp_track_engagement",
    ],
    documentation: "https://developers.facebook.com/docs/instagram/mcp",
    status: "active",
  },
  {
    id: "visual-guidelines",
    name: "Visual Guidelines MCP",
    version: "v1.0.5",
    visibility: "private",
    description: "Brand visual guidelines and design system",
    icon: FileText,
    category: "Design",
    author: "Design Team",
    downloads: "2.1K",
    lastUpdated: "2024-01-15",
    capabilities: [
      "get_color_palette",
      "fetch_typography",
      "validate_design",
      "get_brand_assets",
    ],
    mentions: [
      "@visual_guidelines_get_color_palette",
      "@visual_guidelines_fetch_typography",
      "@visual_guidelines_validate_design",
      "@visual_guidelines_get_brand_assets",
    ],
    documentation: "/docs/internal/visual-guidelines-mcp",
    status: "active",
  },
  {
    id: "campaign-plan",
    name: "Campaign Plan MCP",
    version: "v1.1.2",
    visibility: "private",
    description: "Marketing campaign planning and strategy",
    icon: BarChart3,
    category: "Marketing",
    author: "Marketing Team",
    downloads: "1.8K",
    lastUpdated: "2024-01-14",
    capabilities: [
      "get_quarterly_plan",
      "fetch_campaign_strategy",
      "track_objectives",
      "update_metrics",
    ],
    mentions: [
      "@campaign_plan_get_quarterly_plan",
      "@campaign_plan_fetch_campaign_strategy",
      "@campaign_plan_track_objectives",
      "@campaign_plan_update_metrics",
    ],
    documentation: "/docs/internal/campaign-plan-mcp",
    status: "active",
  },
];
